_appt:
    resource: "@MeetMeApptBundle/Controller/AppointmentController.php"
    type:     annotation
    prefix:   /

_api:
   type: rest
   resource: "@MeetMeApptBundle/Controller/APIController.php"