<?php

namespace MeetMe\ApptBundle\Entity;

use Doctrine\ORM\EntityRepository;
use MeetMe\ApptBundle\Entity\Appointment;

/**
 * AppointmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointmentRepository extends EntityRepository
{
    /**
     * Create a new appointment
     * @param string $title
     * @param datetime $startTime
     * @param datetime $endTime
     * @param string $name
     * @param string $description
     * @param integer $update appointment id to update
     * @return Appointment
     */
    public function createUpdateAppointment($title, $startTime, $endTime, $name = null, $description = null, $update = null){
        if(!$update)
            $appt = new Appointment();
        else
            $appt = $this->findOneBy(array('id' => $update));

        $appt->setTitle($title);
        $appt->setStartTime(\DateTime::createFromFormat('m-d-Y', $startTime));
        $appt->setEndTime(\DateTime::createFromFormat('m-d-Y', $endTime));
        $appt->setName($name);
        $appt->setDescription($description);

        $this->_em->persist($appt);
        $this->_em->flush();

        return $appt;
    }

    /**
     * Remove an appointment
     *
     * @param integer $id appointment id
     * @return bool true if deleted
     */
    public function removeAppointmentById($id){
        $appt = $this->findOneBy(array('id' => $id));
        if($appt){
            $this->_em->remove($appt);
            $this->_em->flush();
            return true;
        }
        return false;
    }
}
